# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: 🚀 Deploy

on:
  workflow_dispatch: {} # manual trigger only

concurrency:
  group: ${{ github.ref }}-deploy
  cancel-in-progress: true

jobs:
  publish:
    name: Publish the site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cloudflare/wrangler-action@v3
        env: {PROJECT_NAME: iddqd-uk-index, DIST_DIR: ./public, CF_BRANCH_NAME: main}
        with:
          apiToken: ${{ secrets.CF_PAGES_DEPLOY_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command:
            pages deploy ${{ env.DIST_DIR }}
            --project-name=${{ env.PROJECT_NAME }}
            --branch ${{ env.CF_BRANCH_NAME }}
            --commit-dirty=true
